[tool.black]
skip-string-normalization = true
target-version = ["py312"] 
include = '\.pyi?$' 
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
)/
'''

[tool.flake8]
exclude = [
    "git",
    "__pycache__",
    "build",
    "dist",
    "venv",
    "tox",
    "mypy_cache"
]
ignore = "E203,W503"
line-length = 162